"area: ci":
  - changed-files:
      - any-glob-to-any-file: ['.github/**']
"area: release":
  - changed-files:
      - any-glob-to-any-file: ['eas.json']
"area: features":
  - changed-files:
      - any-glob-to-any-file: ['app/**']
"area: design-system":
  - changed-files:
      - any-glob-to-any-file: ['app/components/**', 'app/theme/**']
"area: native":
  - changed-files:
      - any-glob-to-any-file: ['modules/**', 'plugins/**', 'ios/**', 'android/**', 'app.config.ts']
"area: docs":
  - changed-files:
      - any-glob-to-any-file: ['**/*.md', 'docs/**']
