plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}
group = 'com.joynnovate.buddybird.sessionaudio'
version = '1.0.0'
android {
  namespace 'com.joynnovate.buddybird.sessionaudio'
  defaultConfig { versionCode 1; versionName '1.0.0' }
  sourceSets { test.java.srcDirs += '../../../test' }
}

dependencies { testImplementation 'junit:junit:4.13.2' }
